unique_ids:
  assets:
    standard-page.html: OTPMJDFSIQZPVECHK5XZJYLAW4H5HUNJ
    theme.css: 2AW3STE4XT6VUBVTEEWQBRJ7BPIDRSY6
  forms:
    Form1: LMZGRYQN6YAEL5UV7MT2DJ2TIFTD6Y3Q
  modules: {}
  scripts: {}
  server_modules: {}
